package com.example.victor.examenestablecimientos;


public class Utilidades {

    public static final String TABLA_ESTABLECIMIENTOS = "CREATE TABLE ESTABLECIMIENTOS (ID_ESTABLECIMIENTO INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE_ESTABLECIMIENTO TEXT , DIRECCION_ESTABLECIMIENTO TEXT ," +
            " TELEFONO TEXT,CORREO TEXT , WEB TEXT ,TIPO TEXT ,NIVEL TEXT ,DIRECTOR TEXT ,ALTITUD TEXT ," +
            "LATITUD TEXT ,CIUDAD TEXT,ENSENANZA TEXT)";

}
